<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;
use App\Models\SchoolAuthority;
class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Agronómica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'1', 'name' =>'Licenciatura en Medicina Veterinaria y Zootecnia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'1', 'name' =>'Maestría en Gestión Integral del Agua', 'director'=>'Pendiete']); */
        School::create(['faculty_id'=>'1', 'name' =>'Arquitectura']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>1]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>1]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Civil']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>2]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>2]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Industrial']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>3]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>3]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Mecánica']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>4]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>4]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Eléctrica']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>5]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>5]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería Química']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>6]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>6]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería de Alimentos']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>7]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>7]);
        School::create(['faculty_id'=>'1', 'name' =>'Ingeniería en Sistemas Informáticos']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>8]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>8]);
        School::create(['faculty_id'=>'1', 'name' =>'Unidad de Ciencias Basicas']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>9]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>9]);
        School::create(['faculty_id'=>'1', 'name' =>'Maestría en Gestión de Recursos Hidrológicos']);
        SchoolAuthority::create(['name'=>'PRUEVA  DIRECTOR','position'=>'DIRECTOR','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>10]);
        SchoolAuthority::create(['name'=>'PRUEVA  SECRETARIO','position'=>'SECRETARIO','startPeriod'=>'2021-02-02','endPeriod'=>'2021-12-02','school_id'=>10]);
        /* School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Geofísica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Biología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Física', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Matemática', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Estadística', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Ciencias Químicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Física', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Licenciatura en Biología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Maestría en Didáctica de la Matemática', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Maestría en Química', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Maestría en Física', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Maestría en Gestión Ambiental', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Manejo Sustentable de los Recursos Naturales Continentales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Profesorado en Ciencias Naturales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Profesorado en Educación Media (enseñanza de la biología)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'3', 'name' =>'Profesorado en Matemática (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Licenciatura en Administración de Empresas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Licenciatura en Contaduría Pública', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Licenciatura en Economía', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Licenciatura en Mercadeo Internacional', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Maestría en Administración de Empresas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'4', 'name' =>'Maestría en Administración Financiera', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'5', 'name' =>'Doctorado en Cirugía Dental', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'6', 'name' =>'Licenciatura en Química y Farmacia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'7', 'name' =>'Licenciatura en Ciencias Jurídicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'7', 'name' =>'Licenciatura en Relaciones Internacionales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'7', 'name' =>'Maestría en Relaciones Internacionales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Doctorado en Medicina', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Laboratorio Clínico', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Anestesiología e Inhaloterapia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Radiología e Imágenes', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Nutrición', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Educación para la Salud', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Ecotecnología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Salud Materno Infantil', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Fisioterapia y Terapia Ocupacional', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Salud Ambiental', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Licenciatura en Enfermería', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Maestría en Salud Pública', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Maestría en Servicios Integrales de Salud Sexual y Reproductiva', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Maestría en Educación, en Salud Sexual y Reproductiva', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Tecnología en Anestesiología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Tecnología en Radiología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Tecnología en Fisioterapia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'8', 'name' =>'Técnico en Laboratorio Clínico', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Arquitectura', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Curso de Formación Pedagógica para Profesionales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Doctorado en Medicina', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Ingeniería Agronómica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Ingeniería Civil', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Ingeniería Industrial', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Ingeniería Mecánica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Ingeniería Eléctrica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Laboratorio Clínico', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Anestesiología e Inhaloterapia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Fisioterapia y Terapia Ocupacional', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Ciencias Jurídicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Educación (educación básica)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Sociología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Psicología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Letras', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Educación', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Química y Farmacia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Economía', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Contaduría Pública', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Administración de Empresas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Matemática', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Estadística', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Ciencias Químicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Física', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Licenciatura en Biología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Educación Parvularia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Educación Básica (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Lenguaje y Literatura (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Idioma Inglés (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Ciencias Sociales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Ciencias Naturales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'9', 'name' =>'Profesorado en Matemática (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Arquitectura', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Doctorado en Medicina', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Curso de Formación Pedagógica para Profesionales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería Civil', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería Industrial', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería Mecánica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería Eléctrica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería Química', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Ingeniería de Sistemas Informáticas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Ciencias Jurídicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Sociología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Psicología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Letras', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Idioma Inglés (enseñanza)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (inglés)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Ciencias del Lenguaje y la Literatura', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (ciencias naturales)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (matemética)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (servicio alternativo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (lenguaje y literatura)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Educación (ciencias sociales)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Química y Farmacia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Contaduría Pública', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Administración de Empresas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Mercadeo Internacional', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Biología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Estadística', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Licenciatura en Ciencias Químicas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Maestrái en Profesionalización de la Docencia Superior', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Maestría en Métodos y Técnicas de Investigación Social', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Maestría en Administración Financiera', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Educación Básica (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Lenguaje y Literatura (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Idioma Inglés (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Ciencias Sociales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Ciencias Naturales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'10', 'name' =>'Profesorado en Matemática (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Ingeniería Agronómica', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Ingeniería de Sistemas Informáticos', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Licenciatura en Educación (ciencias sociales)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Licenciatura en Contaduría Pública', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Educación Parvularia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Educación Básica (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Ciencias Sociales (tercer ciclo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Ciencias Naturales (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Matemática (tercer ciclo y bachillerato)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'11', 'name' =>'Profesorado en Educación Media (biología)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Curso de Formación Pedagógica para Profesionales', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Filosofía', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Filosofía', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Sociología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Psicología', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Letras', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Periodismo', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Idioma Inglés', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Idioma Inglés (enseñanza)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Lenguas Modernas (francés e inglés)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Educación (servicio alternativo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Educación', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Educación (educación f ísica)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Artes Plásticas', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Historia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Trabajo Social', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Licenciatura en Antropología Sociocultural', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestria en Derechos Humanos y Educación para la Paz', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestria en Métodos y Técnicas de Investigación Social', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestría en Traducción (inglés-español / español-inglés)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestría en Didáctica y Formación del Profesorado', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestría en Didáctica para la Formación Docente', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Maestria en Formación para la Docencia Universitaria', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Educación Parvularia', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Educación Básica (primero y segundo ciclos)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Educación Media (enseñanza del inglés)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Lenguaje y Literatura (tercer c iclo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Idioma Inglés (tercer ciclo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Profesorado en Ciencias Sociales (tercer ciclo)', 'director'=>'Pendiete']);
        School::create(['faculty_id'=>'12', 'name' =>'Técnico en Bibliotecología', 'director'=>'Pendiete']);
 */
    }
}
